### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [2]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [3]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [4]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - *your function to illustrate*

In [12]:
# Example 1 - ### your explanation ###

c = torch.randint(low=0, high=10, size=(3,2))
d = torch.randint(low=0, high=10, size=(2,2))
print(c)
print(d)
t_matmul4 = c @ d
print(t_matmul4)

tensor([[9, 0],
        [9, 9],
        [7, 7]])
tensor([[6, 3],
        [5, 0]])
tensor([[54, 27],
        [99, 27],
        [77, 21]])


In [ ]:
# Example 2 - ### your explanation ###
### your code ###

### Function 2 - your function to illustrate

In [ ]:
# Example 1 - ### your explanation ###
### your code ###

In [ ]:
# Example 2 - ### your explanation ###
### your code ###

### Function 3 - your function to illustrate

In [ ]:
# Example 1 - ### your explanation ###
### your code ###

In [ ]:
# Example 2 - ### your explanation ###
### your code ###

### Function 4 - your function to illustrate

In [ ]:
# Example 1 - ### your explanation ###
### your code ###

In [ ]:
# Example 2 - ### your explanation ###
### your code ###